Ensure things compile when F_GET_SEALS is defined
maoe/unix-fcntl pull request #1
Opened 2018-07-25 17:59 UTC by k0001

2018-07-25 23:44 UTC, maoe requested changes
Thanks!

BTW `F_GET_SEALS` isn't available on my systems. What OS are you using?

2018-07-25 23:44 UTC, maoe commented on src/System/Posix/FileControl.hsc
> +newtype Seal = Seal CInt
Could we rename this to `Seals`?

2018-07-26 02:34 UTC, maoe commented
On Ubuntu if F_GET_SEALS seems to be available in linux/fcntl.h but not in fcntl.h.

2018-07-26 07:56 UTC, k0001 commented
Thanks for the quick reply.

I renamed `Seal` to `Seals`.

I am trying to build this on NixOS.

2018-07-26 08:38 UTC, maoe commented
Looks good. Thank you!

Regarding the header files and the availability of the macro, I’ll file a separate ticket.

2018-07-26 08:39 UTC, merged